### ISSUE TITLE
yt auido is not playing

### ISSUE THREAD

**Issue by devsapariya94** [CarlosFdez/SpueBox#5]
when i  do !play <link> [loop?]
it return "Failed to download video: Data could not be retrieved" on discord 
and 
"ERROR: '<https://www.youtube.com/watch?v=dap5lEuS5uM>' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:<https://www.youtube.com/watch?v=dap5lEuS5uM>" ) to search YouTube"

on python shell

**Comment by CarlosFdez** [comment]
This project is currently unmaintained, but the likelyhood is that either the URL/arguments are malformed, or youtube-dl stopped working due to a youtube update. You can try to update packages and see if it works, but last I checked youtube-dl was taken down from a dmca request.

You'd have more luck trying to integrate the project with lavalink/wavelink (which is what rhythm uses internally). I did something like that a while back, but I haven't pushed it to git or tested it recently.

**Comment by devsapariya94** [comment]
ok
